import AuthProvider from "@/providers/auth.provider";
import QueryProvider from "@/providers/query-client.provider";
import { ThemeProvider } from "@/providers/theme-provider";
import ToasterProvider from "@/providers/toaster-provider";
import type { Metadata } from "next";
import { Toaster } from "@/components/ui/toaster";
import "./globals.css";
import { Inter } from "next/font/google";

const Inter_Font = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Madar Admin (Dashboard)",
  description: "Generated by create next app",
};

export default async function RootLayout(
  props: Readonly<{
    children: React.ReactNode;
  }>
) {
  const { children } = props;

  return (
    <html
      // 💡 Prevent next-themes hydration warning
      suppressContentEditableWarning
      suppressHydrationWarning
    >
      <body
        className={`${Inter_Font.className} antialiased`}
        // 💡 Prevent hydration warnings caused by third-party extensions, such as Grammarly.
        suppressHydrationWarning
      >
        {/* tanstack query client provider */}
        <QueryProvider>
          {/* I18n Next-Intl Provider */} {/* Theme Provider */}
          <ThemeProvider>
            {/* Auth Provider */}
            {/* Toaster provider */}
            <ToasterProvider>
              <AuthProvider>{children}</AuthProvider>
            </ToasterProvider>
          </ThemeProvider>
          {/* Redux Store Provider */}
        </QueryProvider>
        <Toaster />
      </body>
    </html>
  );
}
